const fs = require('fs')
const inquirer = require('inquirer')
const {mainQuestions, engineerQuestions, internQuestions} = require("./src/questions")
const Engineer = require('../lib/Engineer')
const Intern = require('../lib/Intern')
const Manager = require('../lib/Manager')
